### PR TITLE
Try fix AR Translation

### PR DESCRIPTION
**Pull request by mostafaalagamy**

### CODE REVIEW

**Comment by Malopieds** [comment]
What the warning meant was you have to add input for zero, one two, few, many, other. So something like this (I know this is wrong but you go the idea):
image

**Comment by mostafaalagamy** [comment]
> What the warning meant was you have to add input for zero, one two, few, many, other. So something like this (I know this is wrong but you go the idea):
> image
>  

I catching the idea, but I translated plurals in the normal way, we don't need that right now.

**Comment by mostafaalagamy** [comment]
Idk ، But the build was successful for me!

**Comment by mostafaalagamy** [comment]
I will try the way that shows the error

**Comment by Malopieds** [comment]
Don't worry, I added ignore annotation, it should fix it!

**Comment by mostafaalagamy** [comment]
> Don't worry, I added ignore annotation, it should fix it!

Thank you:)

**Pull request merged**
