### PR TITLE
Import translations from upstream

### PR DESCRIPTION
**Pull request by lucasmz-dev**

### CODE REVIEW

**Comment by lucasmz-dev** [comment]
@Malopieds Not sure if this helps you? 

The way I merged this was that I cherry-picked every translation-related commit, and then dealt with merge conflicts, I mostly preferred stuff that was sent specifically here, so translations from people that were sent here were prioritized over upstream, especially since there's other strings.

**Comment by lucasmz-dev** [comment]
I wish it didn't show I commited them but I have no idea how to change that / do that without that happening.

**Comment by lucasmz-dev** [comment]
https://github.com/lucasmz-dev/CONTRIB-InnerTune-fork/releases/tag/0.0.6

**Comment by Malopieds** [comment]
Hi, thanks a lot for this !! I first need to add all the other PR before 0.6.0 😅

**Comment by lucasmz-dev** [comment]
@Malopieds should be safe to merge now!

**Comment by Malopieds** [comment]
I might be mistaking but are all the 2 PR the same or not? They both include the upstream changes?

Edit: The other one include upstream changes + your modification so I might take the first one instead of this one?

**Comment by lucasmz-dev** [comment]
You can do that if you want. @Malopieds

**Comment by lucasmz-dev** [comment]
Ideally to prevent merging issues, strings that are in upstream InnerTune would be only translated there, there's now a lot of things that came from here there. I'm not sure if that's possible, I know CalyxOS manages to separate things specific to them and strings from backported features from LineageOS for example, in the same components, just not how.

I could've potentially done a better job merging these more manually, but hm.

**Comment by lucasmz-dev** [comment]
@Malopieds I ended up getting involved in getting Weblate working upstream, and ended up deleting the repo here, anyway in the end I ended up learning a few things and I think we can replicate what I did in OuterTune here, which is separate upstream strings files and fork specific, it made it much easier to get the changes upstream and also contribute back upstream with a common resource, while really making the entire thing less stressful to merge etc, this was essentially what I talked about in the last comment

LMK if you'd like me to go through with this

**Pull request closed without merging**
